services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: musical-chairs-player-app
    container_name: musical-chairs-player-container
    ports:
      - '8080:80'
    restart: unless-stopped
